### ISSUE TITLE
Auto-Posts in #python_jobs weekly

### ISSUE THREAD

**Issue by mattrasband** [pyslackers/sirbot-pythondev#11]
As a community, we would like to help people find jobs and good talent. To enable this, we have decided we want a weekly "Who's Hiring" and "Who's Looking" thread in the #python_jobs channel.

These should be posted automatically, every week, first thing on Monday morning (let's say 8:00am UTC).

depends on pyslackers/sirbot-plugins#9

**Comment by mattrasband** [comment]
We need to think of some copy for this, I think we want a standard template for people to fill out, probably for the "Who's Hiring":


> Company | Job | Location | On-Site/Remote
> Summary...
> Link to job board/company site, etc

**Comment by mattrasband** [comment]
A secondary feature to this, which should be considered and made a ticket, is auto-sharing to the appropriate channels (say if the job is for "flask", share the response in #flask). Though this could just be annoying.

**Comment by ovv** [comment]
It seems a good idea.

I just don't really understand where the template come into the two messages ? 
Just as expected information that should be available ?

**Comment by seanson** [comment]
Would it be good to have these queue up via command?
Running something like `/hiring <company> <title> <location> <on-site/remote>` which would store it in the database and then auto-post at the next selected time, with maybe a weekly user query to find out if this job is still available?

Same thing on the I'm Looking side?

**Comment by mattrasband** [comment]
@ovv The template is just a guideline of what info we'd like to see front and center (location is pretty important since we are a global group). Makes it something we can easily parse and keep around, for example.

@seanson Maybe it's a both and. I like that idea, but I am not sure that most people are used to that format - so may be best to keep it super accessible too. I'd kind of expect posts in a thread to continue all week.

**Comment by ovv** [comment]
I agree with @mrasband. While the command is a nice touch I'm not sure we could expect people to use it.

**Comment by ovv** [comment]
Weekly threads is done.

Still wondering about auto-sharing

**Comment by ovv** [comment]
@mrasband @seanson any input on this ? Or are we ok with how it is now ?

**Comment by mattrasband** [comment]
I think right now it's okay, maybe we close this and revisit later (by filing another ticket for the auto share)
