### ISSUE TITLE
DM formatting not applying when receiving a sirbot notification

### ISSUE THREAD

**Issue by mattrasband** [pyslackers/sirbot-pythondev#34]
<img width="435" alt="screen shot 2017-06-29 at 3 08 00 pm" src="https://user-images.githubusercontent.com/2184696/27710452-06812d1e-5cdd-11e7-9ca0-fc03bf5a0b59.png">

This is what's currently coming through

**Comment by ovv** [comment]
https://github.com/pyslackers/sirbot-pythondev/blob/master/sirbot/pythondev/slack.py#L170

If someone want to give this a shot

**Comment by mattrasband** [comment]
Oh yeah, this is simple - I will grab it. `.format` returns the formatted string, doesn't do it in place.
