### ISSUE TITLE
Update python job weekly message to job_board

### ISSUE THREAD

**Issue by ovv** [pyslackers/sirbot-pythondev#43]

**Comment by smritigambhir** [comment]
Hi. I want to pick this up. I was going through the code. Just wanted to check something:
Do we have to modify this line everywhere in the code?
`message.text = self.config['python_jobs']['looking']`

**Comment by ovv** [comment]
Hey :)

This issue was created because we renamed the `python_jobs` channel to `job_board` and sirbot was hard-coded to post in `python_jobs` so it will not work. To fix that we would need to ask sirbot to post on the new channel [here](https://github.com/pyslackers/sirbot-pythondev/blob/master/sirbot/pythondev/scheduler.py#L23) and [here](https://github.com/pyslackers/sirbot-pythondev/blob/master/sirbot/pythondev/scheduler.py#L36).

This `self.config['python_jobs']['looking']` just get the messages template from the [configuration file](https://github.com/pyslackers/sirbot-pythondev/blob/master/sirbot.yml#L40).
