### ISSUE TITLE
More verbose error messages for /moveto command

### ISSUE THREAD

**Issue by joesanford** [pyslackers/sirbot-pythondev#65]
Currently, `/moveto #not_a_real_channel` will result in the error `Sorry I can not understand the destination.`. The message should be a little more verbose and let users know that only existing channels will work.

**Comment by apex-omontgomery** [comment]
**Two options suggested in slack:**

- NameError: channel name '#name entered' does not exist. Please try another channel, or consult the channel listing on Slack to find an appropriate channel.
- [channel name] does not exist. Please try another channel, or consult the channel listing on Slack to find an appropriate channel.
