### ISSUE TITLE
Check new user email

### ISSUE THREAD

**Issue by ovv** [pyslackers/sirbot-pythondev#71]
On `team_join` we should check the user email is not from a burner domain.
If it is we should post a message in the #admin group.

**Comment by mattrasband** [comment]
Related to #70 (independent but wanted to tag)

**Comment by mattrasband** [comment]
@ovv I am wondering if we disable the heroku invite and make it forward to the website, and the website can do this before any account even gets made. We could require approval before allowing the invite email to be sent if it's "questionable"

**Comment by ovv** [comment]
do we have access to the heroku app ? If yes then yeah it's a better idea.

**Comment by ovv** [comment]
Closing this as it will be done on the website
